<!DOCTYPE html>
<html>
<head>
<title>Inserting Data into my envirowestern Table</title>
</head>
<body style="background-color: rgb(229,243,247);">
<?php
/* This page receives and handles the data generated by "prizeInsert.html". */
// Trim the incoming data.
$uniqueCode = trim($_POST['code']);
$Prize = trim($_POST['prize']);

// Set the variables for the database access:
  require_once('connectvars.php');
// Make a MySQL Connection
$dbc = mysqli_connect(DB_HOST, DB_USER, DB_PASSWORD, DB_NAME);

$query = "INSERT into envirowestern values ('0', '$uniqueCode', '$Prize')";
print ("The query is:<br />$query<br /><br />");

if (mysqli_query ($dbc, $query)) {
 	print "The query was successfully executed!<br />";
} else {
 	print "The query could not be executed!<br />" . mysqli_error($dbc);
}
mysqli_close ($dbc);
?>
</body>
</html>
